export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-50">
      <main className="mx-auto max-w-3xl px-4 py-12">
        <h1 className="text-3xl font-bold text-zinc-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-zinc-600">Last updated: 2026-01-22</p>

        <div className="mt-8 space-y-6 text-sm text-zinc-700">
          <section>
            <h2 className="text-lg font-semibold text-zinc-900">1. Overview</h2>
            <p className="mt-2">
              PlanSureAI provides planning risk assessments and related insights. These outputs are
              guidance only and are not professional planning, legal, or financial advice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">2. AI Disclaimer</h2>
            <p className="mt-2">
              Reports and scores are generated by automated systems and can be incomplete or
              inaccurate. You must verify information with official sources and qualified
              professionals before making decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">3. Accuracy Limitations</h2>
            <p className="mt-2">
              Policy data and comparable applications may be outdated or incomplete. We do not
              guarantee accuracy, completeness, or fitness for a particular purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">4. Subscription & Billing</h2>
            <p className="mt-2">
              Paid plans renew automatically unless cancelled. You may cancel at any time and retain
              access until the end of the billing period. Refunds are handled case-by-case.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">5. Acceptable Use</h2>
            <p className="mt-2">
              You may not scrape, bulk export, or automate access without written permission. You
              must not use the service for unlawful purposes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">6. Intellectual Property</h2>
            <p className="mt-2">
              We own the platform, models, and reports. You retain rights to your uploaded content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">7. Limitation of Liability</h2>
            <p className="mt-2">
              To the maximum extent permitted by law, PlanSureAI is not liable for any losses arising
              from reliance on reports or assessments.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">8. Contact</h2>
            <p className="mt-2">
              Questions about these terms? Contact us at{" "}
              <a className="text-zinc-900 underline" href="mailto:hello@plansureai.com">
                hello@plansureai.com
              </a>
              .
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
